name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    env:
      BIN_DIR: tmp/bin
      TEMP_DIR: tmp/tmp
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu-latest
            short: linux
          - name: macos-latest
            short: darwin
        arch:
          - amd64
          - arm64
    runs-on: ${{ matrix.os.name }}
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        env:
          OS: ${{ matrix.os.short }}
          ARCH: ${{ matrix.arch }}
        run: |
          mkdir -p $BIN_DIR
          mkdir -p $TEMP_DIR
          make test
      - name: List files
        run: |
          echo "--- $BIN_DIR -------------"
          ls -loah $BIN_DIR
          echo "--- $TEMP_DIR ------------"
          ls -loah $TEMP_DIR

